#!/bin/sh
#wifistatus=`ping -c 1 -q google.com > /dev/null; echo $?`
battery=🔋$(acpi | sed 's/Battery 0: //g' | sed 's/, rate information unavailable//g' | sed 's/^[^ ]*[ ]//')
charge=$(acpi)
time=$(date +%H:%M)
day=$(date +%Y/%m/%d)
volume=🔊$(amixer | grep -Eo 'Mono: Playback .{,}%' | sed 's/Mono: Playback ...//g' | sed 's/\[//g') 
brightness=🔆`xbacklight | sed "s/.\{0,7\}$//; /^$/d"`%
amountScreens=`bspc query -M --names | wc -l`
storage=💾`df -Th /dev/nvme0n1p2 | sed '2q;d' | awk -F".94G  " '{print $2}' | awk '{print $1}'`
desktop=$( bspc query -d 'newest:focused' -D --names)
monitor=$( bspc query -d 'newest:focused' -M --names)

expireTime=1500

pkill dunst

battery (){
	case ${charge} in
		*Discharging*) notify-send -t ${expireTime} 🔌🚫${battery};;
		*Full*) notify-send -t ${expireTime} ${battery};;
		*) notify-send -t ${expireTime} 🔌${battery};;
	esac
}

desktopFocus(){
	if [ ${desktop} -gt 5 ]; then
		echo $((${desktop}-5))
	else
		echo ${desktop}
	fi
}

notify-send -t ${expireTime} ${time} ${day}
battery
notify-send -t ${expireTime} ${volume}
if [ ${amountScreens} -eq 1 ]; then
	notify-send -t ${expireTime} ${brightness};
fi
notify-send -t ${expireTime} $(echo $(desktopFocus)"("${monitor}")")
case $(bsp-layout get) in
	-|Tiling)
		notify-send -t ${expireTime} "Default"
		;;
	*)
		notify-send -t ${expireTime} $(bsp-layout get)
		;;
esac
#wifi

